export const superpowers = [
  "flight",
  "speech",
  "invisibility",
  "x-ray vision",
  "headaches",
  "indigestibility",
  "conductivity",
  "absorbency",
  "telekinesis",
  "time travel",
  "telepathy",
  "shape-shifting",
  "super strength",
  "mind control",
  "intangibility",
  "time manipulation",
  "energy projection",
  "regeneration",
  "immortality",
  "comprehensive knowledge of a random subject",
  "dimensional travel",
  "elemental manipulation",
  "teleportation",
  "time freeze",
  "gravity manipulation",
  "magnetism",
  "imperviousness to moss",
  "imperviousness to flattery",
  "truth-telling",
  "clairvoyance",
  "prophesy",
  "teleportation of small objects",
  "teleportation of small animals",
  "speaking in tongues",
  "teleportation, but only of itself",
  "imperviousness to rain",
  "imperviousness to hail",
  "imperviousness to sleet",
  "imperviousness to snow",
  "imperviousness to sun",
  "imperviousness to wind",
  "imperviousness to sand",
  "healing touch",
  "buoyancy",
  "elasticity",
  ];

  export const animals = [
    "aye-aye",
    "numbat",
    "quokka",
    "jerboa",
    "okapi",
    "coelacanth",
    "sea slug Glaucus atlanticus, also known as the blue sea dragon",
    "Sunda colugo",
    "pink fairy armadillo",
    "Irrawaddy dolphin",
    "saola",
    "blobfish",
    "fossa",
    "Japanese spider crab",
    "whistling dhole",
    "maned wolf",
    "narwhal",
    "sloth bear",
    "star-nosed mole",
    "sun bear",
    "axolotl",
    "kakapo",
    "screw-horned goat",
    "fennec fox",
    "pangolin",
    "potoo",
    "potto",
    "copper-tailed starling",
    "shovelnosed guitarfish",
    "screaming hairy armadillo",
    "leaf-tailed gecko",
    "binturong",
    "lowland streaked tenrec",
    "frilled shark",
    "African civet",
    "serval",
    "flying fox",
    "glass frog",
    "ibex",
    "giant anteater",
    "African pangolin",
    "quoll",
    "surinam toad",
    "giant isopod",
    "dik-dik",
    "yeti crab",
    "red-lipped batfish",
    "kinkajou",
    "blue-tongued skink",
    "tufted deer",
    "babirusa",
    "silky anteater",
    "basking shark",
    "harpy eagle",
    "pacu fish",
    "fringe-lipped bat",
    "pied tamarin",
    "gerenuk",
    "Siberian musk deer",
    "marabou stork",
    "Indian purple frog",
    "thorny dragon",
    "spotted hyena",
    "tarsier",
    "gelada baboon",
    "red panda",
    "Honduran white bat",
    "vicuña",
    "long-tailed tit",
    "Pallas's cat",
    "Sunda flying lemur",
    "mara",
    "Brazilian wandering spider",
    "sloth",
    "barreleye fish",
    "African wild dog",
    "mantis shrimp",
    "leafy sea dragon",
    "nudibranch",
    "glasswing butterfly",
    "peacock mantis shrimp",
    "fangtooth fish",
    "pygmy seahorse",
    "hoatzin",
    "hairy frogfish",
    "sarcastic fringehead",
    "secretary bird",
    "wolverine",
    "Malayan colugo",
    "caracal",
    "sea pen",
    "desert rain frog",
    "tawny frogmouth",
    "liger",
    "wombat",
    "Patagonian mara",
]



  export const animalAdjectives = [
    "agile",
    "alert",
    "beautiful",
    "benevolent",
    "courageous",
    "cuddly",
    "curious",
    "dainty",
    "elegant",
    "elusive",
    "fierce",
    "fearsome",
    "gentle",
    "graceful",
    "playful",
    "powerful",
    "shy",
    "sleek",
    "smart",
    "swift",
    "timid",
    "vibrant",
    "wild",
    "charming",
    "colorful",
    "cunning",
    "daring",
    "fascinating",
    "friendly",
    "happy",
    "independent",
    "intelligent",
    "joyful",
    "magnificent",
    "majestic",
    "mysterious",
    "nimble",
    "noble",
    "nocturnal",
    "peaceful",
    "proud",
    "regal",
    "resilient",
    "resourceful",
    "sociable",
    "spirited",
    "sturdy",
    "tenacious",
    "vocal",
    "watchful",
    "wily",
    "zealous",
    "athletic",
    "caring",
    "clever",
    "determined",
    "eagle-eyed",
    "legendary",
    "fast",
    "speedy",
    "loyal",
    "voracious",
    "humble",
    "inquisitive",
    "keen",
    "loyal",
    "mellow",
    "nurturing",
    "observant",
    "patient",
    "protective",
    "restless",
    "sensitive",
    "sly",
    "solitary",
    "strong",
    "tame",
    "tough",
    "wise",
    "adaptable",
    "ambitious",
    "capable",
    "coordinated",
    "endangered",
    "inventive",
    "persistent",
    "trusting",
  ]
  
  export const animalLikeVerbs = [
    'run',
    'swim',
    'fly',
    'eat',
    'sleep',
    'nap',
    'see',
    'hunt',
    'hibernate',
    'migrate',
    'prowl',
    'stalk',
    'nest',
    'burrow',
    'pounce',
    'cavort',
    'wrestle',
    'slither',
    'crawl',
    'jump',
    'hide',
    'climb',
    'perch',
    'soar',
    'scuttle',
    'scurry',
    'dive',
    'build intricate nests',
    'sing',
    'chirp',
    'howl',
    'growl',
    'squeak',
    'bark',
    'whistle',
    'graze',
    'vocalize',
  ];

  export const animalVerbs = [
    "pet",
    "feed",
    "train",
    "see",
    "commune with",
    "empathize with",
    "ride",
    "talk to",
    "care for",
    "hug",
    "milk",
    "walk with",
    "play with",
    "groom",
    "ride on",
    "study",
    "sing to",
    "watch over",
    "swim with",
    "cuddle with",
    "race",
    "handle",
    "feed treats to",
    "speak to",
    "communicate with",
    "heal",
    "train",
    "track",
    "learn from",
    "herd",
    "whisper to",
    "understand",
    "ride on the back of",
    "feed",
    "command",
    "coexist with",
    "summon",
    "detect",
    "repel",
  ]

  export const remotePlaces = [
    "Socotra Island",
    "Mount Roraima",
    "Santorini",
    "Antelope Canyon",
    "Cenotes of Yucatan Peninsula",
    "the Giant's Causeway",
    "Mount Erebus",
    "Cappadocia",
    "the Bermuda Triangle",
    "Easter Island",
    "the Nazca Lines",
    "Fingal's Cave",
    "Pamukkale",
    "the Cave of Crystals",
    "the Skeleton Coast",
    "the Eye of Africa",
    "Bled Island",
    "Devil's Bridge",
    "Mount Teide",
    "Trolltunga",
    "the Waitomo Glowworm Caves",
    "Kamchatka",
    "Eternal Flame Falls",
    "Pike's Peak",
    "Cape Cod",
    "Saskatchewan",
    "Brazil",
    "Ys",
    "Atlantis",
    "the Bering Straits",
    "Mount Huashan",
    "Salar de Uyuni",
    "Göreme",
    "Mount Kailash",
    "Chiribiquete",
    "Tsingy de Bemaraha",
    "Skaftafell Ice Cave",
    "the Bisti Badlands",
    "Mount Thor",
    "Jellyfish Lake",
    "Blood Falls",
    "Stone Forest of Shilin",
    "Zhangjiajie",
    "Hua Shan",
    "Mount Ossa",
    "Cerro Torre",
    "Eureka Dunes",
    "Batu Caves",
    "Benagil Sea Cave",
    "Puerto Princesa Underground River",
    "the Mendenhall Ice Caves",
    "Reed Flute Cave",
    "Devetashka Cave",
    "Mount Cook",
    "the Valley of the Moon",
    "Marble Caves",
    "the Apostle Islands Sea Caves",
    "the Tianzi Mountains",
    "the banded hills of the Zhangye Danxia",
    "Monument Valley",
    "Cerro Fitz Roy",
    "Lencois Maranhenses",
    "Sossusvlei",
    "Mount Fitz Roy",
    "Mount Assiniboine",
    "Bryce Canyon",
    "Mount McKinley",
    "Mount Whitney",
    "Mount Logan",
    "Angel Falls",
    "Mount Olympus",
    "the Siberian Steppes",
    "the Alaskan Interior",
    "Manchuria",
    "the Matterhorn",
    "Mount Ararat",
    "Mount Kilimanjaro",
    "Denali",
    "Puncak Jaya",
    "Mount Elbrus",
    "Puncak Trikora",
    "Puncak Mandala",
    "Chomolungma",
    "Ama Dablam",
    "Cerro Mercedario",
    "Monte Rosa",
    "the Grand Tetons",
    "Cerro Aconcagua",
    "Torres del Paine",
    "Cerro Bonete",
    "Mount Saint Elias",
    "Cerro Solo",
    "Devils Tower",
    "Cerro La Silla",
    "Mount Shasta",
    "Cerro Catedral",
    "Mount Aragats",
    "Mount Gongga",
    "Cerro El Juncal",
    "Cerro Bayo",
    "Babylon",
    "Athens",
    "Rome",
    "Thebes",
    "Jerusalem",
    "Ephesus",
    "Sparta",
    "Carthage",
    "Troy",
    "Alexandria",
    "Nineveh",
    "Persepolis",
    "Memphis",
    "Ur",
    "Mohenjo-Daro",
    "Machu Picchu",
    "Teotihuacan",
    "Pompeii",
    "Chichen Itza",
    "Palmyra",
    "Ebla",
    "Uruk",
    "Byblos",
    "Luxor",
    "Hattusa",
    "Knossos",
    "Akhetaten",
    "Pataliputra",
    "Bactra",
    "Susa",
    "Heliopolis",
    "Nippur",
    "Merv",
    "Sogdiana",
    "Samarkand",
    "Herculaneum",
    "Tikal",
    "Petra",
    "Tiwanaku",
    "Hattusha",
    "Lhasa",
    "Hermopolis",
    "Ugarit",
    "Caracol",
  ]