export const harms = [
  'ingest',
  'eat',
  'expose to sunlight',
  'jostle',
  'handle',
  'inhale',
  'smoke',
  'ignite',
  'pierce',
  'mix with water',
  'shake vigorously',
  'store near heat source',
  'leave in direct sunlight',
  'allow to come into contact with skin',
  'store in a pressurized container',
  'immerse in water',
  'heat in a closed container',
  'freeze in a sealed container',
  'expose to an open flame',
  'inhale fumes',
  'apply pressure',
  'store in a crowded space',
  'store in a glass container',
  'store in a plastic container',
  'use near open flames',
  'taste or lick',
  'apply to open wounds',
  'mix with other chemicals',
  'pour down the drain',
  'dispose of in regular trash',
  'dispose of in a landfill',
  'dispose of in a body of water',
  'dispose of in a fire',
  'recycle',
  'apply to eyes',
  'store with incompatible substances',
  'store with food items',
  'store in a humid environment',
  'store near nickel',
  'store near bismuth',
  'store near salt water',
  'store near fresh water',
  'store near ammonium chloride',
  'store with medication',
  'take on a sea voyage',
  'store in glass flasks',
  'store in oaken chests',
  'mix with cleaning agents',
  'store in a humid environment',
  'store in a hot environment',
  'store near electronic devices',
  'store near children or pets',
  'store near reactive materials',
  'breathe in the vapors',
  'store in a poorly ventilated area',
  'consume or drink',
  'touch with bare hands',
  'store in a metal container',
  'store in a glass container',
  'store in a flammable area',
  'look directly at it',
  'use under the influence of alcohol',
  'use without a license',
  'sell without a license',
  'store in a glass case',
  'photograph',
  'photograph with a flash',
  'touch with a graphite pencil',
  'drop',
  'store in a brightly-lit area',
  'gaze too deeply at it',
];

export const caveats = [
  'unless trained by a physician',
  'without rubber gloves',
  'without proper training',
  'while riding a train',
  'while riding a bicycle',
  'while in an airplane',
  'while in a pressurized environment',
  'while near power lines',
  'in microgravity',
  'near a nuclear reactor',
  'near a beaver dam',
  'without shaking it first',
  'in a school building',
  'at home',
  'while eating cheese',
  'near whales',
  'while sleeping',
  'in a tree',
  'without wearing goggles',
  'without wearing gloves',
  'without appropriate headgear',
  'while wearing fur',
  'while using electronic devices',
  'near a hydroelectric generator',
  'without wearing socks',
  'while wearing red clothing',
  'in a thunderstorm',
  'in a library',
  'in a crowded elevator',
  'near a volcano',
  'in a haunted house',
  'during a tornado',
  'in a hot air balloon',
  'in the dark',
  'in a crowded subway',
  'during a hurricane',
  'in a cave',
  'near a cliff edge',
  'near an active volcano',
  'during a lightning storm',
  'while handling optics',
  'near lasers of any power',
  "unless you're absolutely certain",
]