export const owners = [
  "Catarina of Portugal",
  "Queen Victoria",
  "Elisabeth of Austria",
  "Catherine the Great",
  "Prince Albert",
  "Napoleon III",
  "Empress Eugénie of France",
  "Frederick II of Prussia",
  "Frederick William I of Prussia",
  "Empress Maria Theresa",
  "Catherine Howard",
  "the Duke of Marlborough",
  "Marie Antoinette",
  "Louis XVI",
  "Empress Marie Louise",
  "Josephine de Beauharnais",
  "the Duchess of Lucca",
  "Isabella II of Spain",
  "Ferdinand VII of Spain",
  "Alfonso XII of Spain",
  "Ferdinand II of Germany",
  "Alfonso XIII of Spain",
  "George I of Greece",
  "Olga Constantinovna",
  "Otto von Bismarck",
  "Czar Alexander II",
  "Czar Nicholas II",
  "Empress Alexandra Feodorovna",
  "Augusta of Germany",
  "Frederick III",
  "Victoria of Germany",
  "Augusta Victoria of Germany",
  "Emperor Meiji",
  "Empress Shoken",
  "Hirohito, Emperor Showa",
  "Emperor Taisho",
  "Philip IV of Spain",
  "Maria Anna of Spain",
  "Charles II of Spain",
  "Philip V of Spain",
  "Elisabeth of France",
  "Louise-Élisabeth of France",
  "Maria Josepha of Saxony",
  "Marie Thérèse of France",
  "Louis XVII",
  "Louis XVIII",
  "Charles X of France",
  "Louis Antoine, Duke of Angoulême",
  "Charles Ferdinand, Duke of Berry",
  "Henry IV of France",
  "Marie de' Medici",
  "Louis XIII",
  "Anne of Austria",
  "Philippe I, Duke of Orléans",
  "Louis Philippe I",
  "Marie-Amélie of Bourbon",
  "Napoleon II",
  "Margaret of Valois",
  "Henry II of France",
  "Mary, Queen of Scots",
  "Louis I of Spain",
  "Isabella Clara Eugenia of Spain",
  "Albert VII, Archduke of Austria",
  "Ferdinand VI of Spain",
  "Charles III of Spain",
  "Amadeo I of Spain",
  "Maria Christina of Austria",
  "Christian IX of Denmark",
  "Queen Louise of Denmark",
  "Constantine I of Greece",
  "Sophia of Prussia",
  "Alexandra of Denmark",
  "Edward VII",
  "George V",
  "Mary of Teck",
  "Prince Albert Victor",
  "Alice Keppel",
  "Prime Minister Lloyd George",
  "Edward VIII",
  "Winston Churchill",
  "Baroness Spencer-Churchill",
  "George VI",
  "The Queen Mother",
  'Shah Jahan',
  'Emperor Aurangzeb',
  'Tipu Sultan, the Tiger of Mysore',
  'Rani Padmini of Mewar',
  'Shivaji I',
  'Bahadur Shah II',
  'King Rama I',
  'The Kangxi Emperor',
  'The Qianlong Emperor',
  'Emperor Meiji',
  'Emperor Taisho',
  'The Xuantong Emperor, Puyi',
  'King Taksin the Great',
  'Mongkut, King Rama IV',
  'Chulalongkorn, King Rama V',
  'King Mahendra',
  'Tribhuvan of Nepal',
  'an Emperor "Taizu", but no one knows which',
  'The Hongzhi Emperor',
  'The Zhengde Emperor',
  'the Wanli Emperor',
  'The Tianqi Emperor',
  'The Yongzheng Emperor',
  'Empress Dowager Cixi',
  "Empress Dowager Ci'an",
  'Emperor Hirohito',
  'Emperor Gojong',
  'Emperor Sunjong',
  'Empress Myeongseong',
  'King Sejong the Great',
  'King Yeonsangun',
  'King Jungjong',
  'King Injong of Joseon',
  'King Sukjong of Joseon',
  'King Yeongjo',
  'King Jeongjo',
  'Atahualpa',
  'Atahualpa',
  'Dom Pedro II',
  'Shaka Zulu',
  'Menelik II',
  'Osei Kofi Tutu I',
  'Ahmad al-Mansur',
  'Simón Bolívar',
  'Haile Selassie',
  'José de San Martín',
  "Bernardo O'Higgins",
  'Tupac Amaru II',
  'Dom João VI',
  'Yaa Asantewaa',
  'Cetshwayo kaMpande',
  'Tewodros II',
  'Tiradentes',
  'Emperor Pedro I'
]