  module.exports = [
    'grave',
    'cave',
    'temple',
    'sewer',
    'sofa',
    'crevice',
    'mine',
    'deposit',
    'bank vault',
    'chest',
    'warren',
    'burrow',
    'desk drawer',
    'boat',
    'mausoleum',
    'attic',
    'mansion',
    'shipyard',
    'mill',
    'compartment',
    'ammunition dump',
    'treasure chest',
    'shipwreck',
    'city',
    'submarine',
    'storehouse',
    'library',
    'basement',
    'tunnel',
    'chamber',
    'ruin',
    'ship',
    'island',
    'tomb',
    'garden',
    'mine shaft',
    'castle',
    'warehouse',
    'pharmacy',
    'catacomb',
    'cavern',
    'staircase',
    'grotto',
    'bunker',
    'waterfall',
    'pool',
    'pond',
    'river',
    'museum',
    'auction house',
    'lighthouse',
    'subterranean river',
    'monastery',
    'convent',
    'laboratory',  
]