export const superpowers = [
  "flight",
  "speech",
  "invisibility",
  "x-ray vision",
  "headaches",
  "indigestibility",
  "conductivity",
  "absorbency",
  "telekinesis",
  "time travel",
  "telepathy",
  "shape-shifting",
  "super strength",
  "mind control",
  "intangibility",
  "time manipulation",
  "energy projection",
  "regeneration",
  "immortality",
  "comprehensive knowledge of a random subject",
  "dimensional travel",
  "elemental manipulation",
  "teleportation",
  "time freeze",
  "gravity manipulation",
  "magnetism",
  "imperviousness to moss",
  "imperviousness to rain",
  "imperviousness to hail",
  "imperviousness to sleet",
  "imperviousness to snow",
  "imperviousness to sun",
  "imperviousness to wind",
  "imperviousness to sand",
  "healing touch",
  "buoyancy",
  "elasticity",
  ];

  export const animals = [
    "Aye-Aye",
    "Numbat",
    "Quokka",
    "Jerboa",
    "Okapi",
    "Coelacanth",
    "Glaucus Atlanticus",
    "Sunda Colugo",
    "Pink Fairy Armadillo",
    "Irrawaddy Dolphin",
    "Saola",
    "Blobfish",
    "Fossa",
    "Japanese Spider Crab",
    "Dhole",
    "Maned Wolf",
    "Narwhal",
    "Sloth Bear",
    "Star-Nosed Mole",
    "Sun Bear",
    "Axolotl",
    "Kakapo",
    "Markhor",
    "Fennec Fox",
    "Pangolin",
    "Potoo",
    "Leaf-Tailed Gecko",
    "Binturong",
    "Lowland Streaked Tenrec",
    "Frilled Shark",
    "African Civet",
    "Serval",
    "Flying Fox",
    "Glass Frog",
    "Ibex",
    "Giant Anteater",
    "African Pangolin",
    "Quoll",
    "Surinam Toad",
    "Giant Isopod",
    "Dik-Dik",
    "Yeti Crab",
    "Red-Lipped Batfish",
    "Kinkajou",
    "Blue-Tongued Skink",
    "Tufted Deer",
    "Babirusa",
    "Silky Anteater",
    "Basking Shark",
    "Harpy Eagle",
    "Pacu Fish",
    "Fringe-Lipped Bat",
    "Pied Tamarin",
    "Gerenuk",
    "Siberian Musk Deer",
    "Marabou Stork",
    "Indian Purple Frog",
    "Thorny Dragon",
    "Spotted Hyena",
    "Tarsier",
    "Gelada Baboon",
    "Red Panda",
    "Honduran White Bat",
    "Vicuña",
    "Long-Tailed Tit",
    "Pallas's Cat",
    "Sunda Flying Lemur",
    "Mara",
    "Brazilian Wandering Spider",
    "Sloth",
    "Barreleye Fish",
    "African Wild Dog",
    "Mantis Shrimp",
    "Leafy Sea Dragon",
    "Nudibranch",
    "Glasswing Butterfly",
    "Peacock Mantis Shrimp",
    "Fangtooth Fish",
    "Pygmy Seahorse",
    "Hoatzin",
    "Hairy Frogfish",
    "Sarcastic Fringehead",
    "Secretary Bird",
    "Wolverine",
    "Malayan Colugo",
    "Caracal",
    "Sea Pen",
    "Desert Rain Frog",
    "Tawny Frogmouth",
    "Liger",
    "Wombat",
    "Patagonian Mara",
  ]


  export const animalAdjectives = [
    "agile",
    "alert",
    "beautiful",
    "benevolent",
    "courageous",
    "cuddly",
    "curious",
    "dainty",
    "elegant",
    "elusive",
    "fierce",
    "fearsome",
    "gentle",
    "graceful",
    "playful",
    "powerful",
    "shy",
    "sleek",
    "smart",
    "swift",
    "timid",
    "vibrant",
    "wild",
    "charming",
    "colorful",
    "cunning",
    "daring",
    "fascinating",
    "friendly",
    "happy",
    "independent",
    "intelligent",
    "joyful",
    "magnificent",
    "majestic",
    "mysterious",
    "nimble",
    "noble",
    "nocturnal",
    "peaceful",
    "proud",
    "regal",
    "resilient",
    "resourceful",
    "sociable",
    "spirited",
    "sturdy",
    "tenacious",
    "vocal",
    "watchful",
    "wily",
    "zealous",
    "athletic",
    "caring",
    "clever",
    "determined",
    "eagle-eyed",
    "legendary",
    "fast",
    "speedy",
    "loyal",
    "voracious",
    "humble",
    "inquisitive",
    "keen",
    "loyal",
    "mellow",
    "nurturing",
    "observant",
    "patient",
    "protective",
    "restless",
    "sensitive",
    "sly",
    "solitary",
    "strong",
    "tame",
    "tough",
    "wise",
    "adaptable",
    "ambitious",
    "capable",
    "coordinated",
    "endangered",
    "inventive",
    "persistent",
    "trusting",
  ]
  
  export const animalLikeVerbs = [
    'feed',
    'run',
    'swim',
    'fly',
    'eat',
    'sleep',
    'nap',
    'see',
    'hunt',
    'hibernate',
    'migrate',
    'prowl',
    'stalk',
    'nest',
    'burrow',
    'pounce',
    'cavort',
    'wrestle',
    'slither',
    'crawl',
    'jump',
    'hide',
    'climb',
    'perch',
    'soar',
    'scuttle',
    'scurry',
    'dive',
    'build',
    'sing',
    'chirp',
    'howl',
    'growl',
    'squeak',
    'bark',
    'whistle',
    'graze',
    'vocalize',
  ];

  export const animalVerbs = [
    "pet",
    "feed",
    "train",
    "see",
    "commune with",
    "adopt",
    "empathize with",
    "ride",
    "talk to",
    "adopt",
    "care for",
    "observe",
    "hug",
    "milk",
    "walk with",
    "play with",
    "groom",
    "ride on",
    "study",
    "sing to",
    "watch over",
    "swim with",
    "cuddle with",
    "race",
    "handle",
    "feed treats to",
    "speak to",
    "communicate with",
    "heal",
    "train",
    "track",
    "learn from",
    "admire",
    "examine",
    "herd",
    "whisper to",
    "understand",
    "ride on the back of",
    "feed",
    "command",
    "coexist with",
  ]

  export const remotePlaces = [
    "Socotra Island",
    "Mount Roraima",
    "Santorini",
    "Antelope Canyon",
    "Cenotes of Yucatan Peninsula",
    "the Giant's Causeway",
    "Mount Erebus",
    "Cappadocia",
    "the Bermuda Triangle",
    "Easter Island",
    "the Nazca Lines",
    "Fingal's Cave",
    "Pamukkale",
    "the Cave of Crystals",
    "the Skeleton Coast",
    "the Eye of Africa",
    "Bled Island",
    "Devil's Bridge",
    "Mount Teide",
    "Trolltunga",
    "the Waitomo Glowworm Caves",
    "Kamchatka Peninsula",
    "Eternal Flame Falls",
    "Pike's Peak",
    "Cape Cod",
    "Saskatchewan",
    "Brazil",
    "Ys",
    "Atlantis",
    "the Bering Straits",
    "Mount Huashan",
    "Salar de Uyuni",
    "Göreme",
    "Mount Kailash",
    "Chiribiquete",
    "Tsingy de Bemaraha",
    "Skaftafell Ice Cave",
    "the Bisti Badlands",
    "Mount Thor",
    "Jellyfish Lake",
    "Blood Falls",
    "Stone Forest of Shilin",
    "Zhangjiajie",
    "Hua Shan",
    "Mount Ossa",
    "Cerro Torre",
    "Eureka Dunes",
    "Batu Caves",
    "Benagil Sea Cave",
    "Puerto Princesa Underground River",
    "the Mendenhall Ice Caves",
    "Reed Flute Cave",
    "Devetashka Cave",
    "Mount Cook",
    "the Valley of the Moon",
    "Marble Caves",
    "the Apostle Islands Sea Caves",
    "the Tianzi Mountains",
    "the banded hills of the Zhangye Danxia",
    "Monument Valley",
    "Cerro Fitz Roy",
    "Lencois Maranhenses",
    "Sossusvlei",
    "Mount Fitz Roy",
    "Mount Assiniboine",
    "Bryce Canyon",
    "Mount McKinley",
    "Mount Whitney",
    "Mount Logan",
    "Angel Falls",
    "Mount Olympus",
    "the Siberian Steppes",
    "the Alaskan Interior",
    "Manchuria",
    "Matterhorn",
    "Mount Ararat",
    "Mount Kilimanjaro",
    "Denali",
    "Puncak Jaya",
    "Mount Elbrus",
    "Puncak Trikora",
    "Puncak Mandala",
    "Chomolungma",
    "Ama Dablam",
    "Cerro Mercedario",
    "Monte Rosa",
    "the Grand Tetons",
    "Cerro Aconcagua",
    "Torres del Paine",
    "Cerro Bonete",
    "Mount Saint Elias",
    "Cerro Solo",
    "Devils Tower",
    "Cerro La Silla",
    "Mount Shasta",
    "Cerro Catedral",
    "Mount Aragats",
    "Mount Gongga",
    "Cerro El Juncal",
    "Cerro Bayo",
    "Babylon",
    "Athens",
    "Rome",
    "Thebes",
    "Jerusalem",
    "Ephesus",
    "Sparta",
    "Carthage",
    "Troy",
    "Alexandria",
    "Nineveh",
    "Persepolis",
    "Memphis",
    "Ur",
    "Mohenjo-Daro",
    "Machu Picchu",
    "Teotihuacan",
    "Pompeii",
    "Chichen Itza",
    "Palmyra",
    "Ebla",
    "Uruk",
    "Byblos",
    "Luxor",
    "Hattusa",
    "Knossos",
    "Akhetaten",
    "Pataliputra",
    "Bactra",
    "Susa",
    "Heliopolis",
    "Nippur",
    "Merv",
    "Sogdiana",
    "Samarkand",
    "Herculaneum",
    "Tikal",
    "Petra",
    "Tiwanaku",
    "Hattusha",
    "Lhasa",
    "Hermopolis",
    "Ugarit",
    "Caracol",
  ]