export const makes = [
  "Buick",
  "Cadillac",
  "Chrysler",
  "Pontiac",
  "Studebaker",
  "Nash",
  "Hudson",
  "Packard",
  "Willys",
  "Oldsmobile",
  "DeSoto",
  "Plymouth",
  "Kaiser-Frazer",
  "Tucker",
  "Hupmobile",
  "Nash-Healey",
  "Crosley",
  "Hudson-Essex",
  "Rambler",
  "Kaiser",
  "Stutz",
  "Duesenberg",
  "Stearns-Knight",
  "Auburn",
  "LaSalle",
  "Oakland",
  "Franklin",
  "Winton",
  "Marmon",
  "Peerless",
  "Hudson",
  "Essex",
  "Overland",
  "Maxwell",
  "Durant",
  "Nash Metropolitan",
  "Reo",
  "Cord",
  "Graham-Paige",
  "Willys-Knight",
  "Stutz Bearcat",
  "Lozier",
  "Kissel",
];

export const models = [
  "Ford Model T",
  "Chevrolet Series 490",
  "Dodge Brothers Touring Car",
  "Buick Series 10",
  "Cadillac Type 53",
  "Chrysler Six",
  "Pontiac Chief",
  "Studebaker Special Six",
  "Nash Advanced Six",
  "Hudson Super Six",
  "Packard Twin Six",
  "Willys-Knight Great Six",
  "Oldsmobile Model 30",
  "DeSoto Custom",
  "GMC C/K Series",
  "Plymouth Model Q",
  "International Harvester Scout",
  "Kaiser Special",
  "Tucker 48",
  "Hupmobile Series R",
  "Nash-Healey",
  "Crosley Hotshot",
  "Hudson-Essex Terraplane",
  "Rambler Model B",
  "Kaiser Virginian",
  "Stutz Bearcat",
  "Duesenberg Model J",
  "Stearns-Knight H6-80",
  "Auburn 851",
  "LaSalle Series 50",
  "Oakland Sensible Six",
  "Franklin Airman",
  "Winton Six",
  "Marmon Model 34",
  "Peerless Six",
  "Hudson Terraplane Eight",
  "Hudson Super Six",
  "Essex Super Six",
  "Overland Model 90",
  "Maxwell Model 25",
  "Durant Model A-22",
  "Nash Metropolitan",
  "Reo Flying Cloud",
  "Cord L-29",
  "Graham-Paige Model 610",
  "Willys-Knight 70A",
  "Stutz Bearcat",
  "Lozier Briarcliff",
  "Kissel Gold Bug Speedster",
];

export const types = [
  'Coupe',
  'Roadster',
  'Sedan',
  'Convertible',
  'Limousine',
  'lorry',
  'Tudor',
  'Phaeton',
  'Touring Car',
  'Grand Tourer',
  'Racer',
  'Speedster',
];