export const conditions = [
  'in salt water',
  'with a low noise',
  'at dusk',
  'at daybreak',
  'in your grasp',
  'when exposed to oxygen',
  'at night',
  'during thunderstorms',
  'when bitten',
  'when dropped',
  'when struck with a hammer',
  'when struck',
  'in large numbers',
  'when rubbed with a felt cloth',
  'under a full moon',
  'on hot summer days',
  'on cold winter nights',
  'in complete darkness',
  'at high noon',
  'in crowded rooms',
  'when crushed and mixed with water',
  'during a solar eclipse',
  'during a lunar eclipse',
  'when covered in snow',
  'in the rain',
  'during hailstorms',
  'in the heat of battle',
  'under a new moon',
  'when heated to a high temperature',
  'when cooled to a low temperature',
  'in a vacuum',
  'in outer space',
  'during volcanic eruptions',
  'in a laboratory setting',
  'under a microscope',
  'when viewed from a distance',
  'when illuminated by a bright light',
  'when forgotten',
  'when exposed to ultraviolet light',
  'when submerged in oil',
  'when wrapped in a cloth',
  'when struck by lightning',
  'during a total eclipse of the sun',
  'when subjected to extreme pressure',
  'when observed by a scientist',
  'when sat upon by a bird',
  'in the presence of royalty',
  'in a magnetic field',
  'when subjected to electric current',
]

export const gemverbs = [
  'floats',
  'hums',
  'sparkles',
  'glints',
  'creaks',
  'ticks',
  'gleams',
  'wriggles',
  'shimmers',
  'glistens',
  'vibrates',
  'resonates',
  'sings',
  'whispers',
  'pulses',
  'radiates',
  'shines',
  'dances',
  'twinkles',
  'flashes',
  'pops',
  'degrades',
  'grows',
  'thrives',
  'withers',
  'crumbles',
  'cracks',
  'buzzes',
  'echoes',
  'rumbles',
  'warms the hands',
  'chills the hands',
  'pulses',
  'rotates',
  'levitates',
  'pings',
  'shudders',
  'glows',
  'scintillates',
  'flickers',
  'changes color',
  'crackles',
  'glimmers',
  'breathes',
  'expands',
  'contracts',
  'buzzes',
  'sweats',
  'rattles',
  'jitters',
  'trembles',
  'fizzes',
  'bubbles',
  'refracts ultraviolet light',
  'focuses moonlight',
  'calms the mind',
  'tells fortunes',
  'predicts the weather',
  'glimmers like moonlight',
  'smells faintly like socks',
  'fades',
  'brightens',
  'reddens',
  'emits noxious fumes',
  'turns purple',
  'turns bright orange',
  'shimmers like a star',
  'sharply retracts',
  'burrows deeply into the ground',  
]
