module.exports = [
  "Rabindranath Tagore",
  "Amrita Sher-Gil",
  "Sri Chinmoy",
  "Fazlur Rahman Khan",
  "Tamerlane",
  "the servant of Hafez",
  "Tipu Sultan",
  "a descendant of Nizamuddin Auliya",
  "Sarvepalli Radhakrishnan",
  "Vidyapati",
  "Rasputin",
  "Lucrezia Borgia",
  "Aleister Crowley",
  "Baron Münchhausen",
  "Mary Toft",
  "Pope Alexander VI",
  "the infamous Conrad V. Zollbrecht",
  "John Dee",
  "Rasputin's daughter",
  "Richard Lawrence",
  "Matthew Hopkins",
  "the pirate Walter Kennedy",
  "the Countess de la Motte",
  "Mary Frith",
  "the Countess of Desmond",
  "H. H. Holmes",
  "Isobel Gowdie",
  "Bunko Kelly",
  "Kaspar Hauser",
  "Roaring Dan Seavey",
  "Felix Faure",
  "Pancho Villa",
  "Tsar Paul I of Russia",
  "Luigi Lucheni",
  "Pier Gerlofs Donia",
  "Alix of Hesse",
  "Moll Pitcher",
  "Johann Georg Faust",
  "Prince Rupert of the Rhine",
  "Pope Joan",
  "Jean de Dunois",
  "Caterina Sforza",
  "Ma Barker",
  "Ivan the Terrible",
  "James MacLaine",
  "Horace Walpole's mother",
  "one Robert Cochrane",
  "Ludovico Sforza",
  "Louis Antoine de Saint-Just",
  "Jacques de Molay",
  "Billy Miner, the Gentleman Bandit",
  "Paganini",
  "the botanist Karl Koch",
  "William the Silent",
  "the notorious Conrad V. Zollbrecht",
  "Marianne Weber",
  "Clarence Hatry",
  "Antoine Lavoisier",
  "Felix Weil",
]
