export const pies = [
  'blueberry',
  'grape',
  'apple',
  'cherry',
  'weasel',
  'peach',
  'sausage',
  'herbal',
  'blackbird',
  'steak and kidney',
  'blackberry',
  'boysenberry',
  'cloudberry',
  'salmonberry',
  'raspberry',
  'strawberry',
  'banana cream',
  'lemon meringue',
  'coconut cream',
  'pecan',
  'pumpkin',
  'fig',
  'rhubarb',
  'cranberry',
  'mango',
  'apricot',
  'pear',
  'strawberry rhubarb',
  'lime',
  'passion fruit',
  'pineapple',
  'elderberry',
  'loganberry',
  'guava',
  'date',
];